version: "3"
services:

  auth-db:
    image: postgres:14
    container_name: db-local
    restart: always
    networks:
      - routes-map-network
    environment:
      - POSTGRES_DB=db-local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
networks:
  routes-map-network:
    driver: bridge